name = "family-pop"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[durable_objects.bindings]]
name = "FAMILY"
class_name = "Family"

[[durable_objects.bindings]]
name = "DIR"
class_name = "Directory"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Family", "Directory"]

[triggers]
crons = ["0 14,18 * * *"]

[vars]
VAPID_PUBLIC = "BCc84ZqpAZSLf-m-K-nPiToUtwyEx3Z8Eyg-jU4YHDPUcYkS8Iyhec9ZxtIc-swb_ZvAEjuq_YsWJZEteLDEq6Q"
